# Generated by Django 3.1.7 on 2021-03-24 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic', models.ImageField(upload_to='main-photo')),
                ('name', models.CharField(max_length=30)),
                ('mname', models.CharField(blank=True, max_length=50, null=True)),
                ('lname', models.CharField(blank=True, max_length=50, null=True)),
                ('designation', models.CharField(blank=True, max_length=256, null=True)),
                ('age', models.PositiveIntegerField()),
                ('country', models.CharField(max_length=50)),
                ('state', models.CharField(blank=True, max_length=50, null=True)),
                ('address', models.CharField(blank=True, max_length=256, null=True)),
                ('email', models.EmailField(max_length=256)),
                ('phone', models.CharField(blank=True, max_length=25, null=True)),
                ('description', models.CharField(max_length=500)),
            ],
        ),
    ]
