# Generated by Django 3.1.7 on 2021-03-24 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_core', '0002_profile_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eduTitle', models.CharField(max_length=50)),
                ('eduFrom', models.CharField(max_length=100)),
                ('eduYear', models.PositiveIntegerField(max_length=10)),
                ('eduDesc', models.CharField(blank=True, max_length=256, null=True)),
                ('eduFor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_core.profile')),
            ],
        ),
    ]
