# Generated by Django 3.1.7 on 2021-03-24 22:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_core', '0004_auto_20210325_0248'),
    ]

    operations = [
        migrations.CreateModel(
            name='skils',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skilTitle', models.CharField(max_length=50)),
                ('skilPer', models.IntegerField(default=1)),
                ('skilFor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_core.profile')),
            ],
        ),
    ]
