# Generated by Django 3.1.7 on 2021-03-24 23:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_core', '0005_skils'),
    ]

    operations = [
        migrations.CreateModel(
            name='knowledge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('knowledges', models.CharField(max_length=500)),
                ('knoFor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_core.profile')),
            ],
        ),
    ]
