# Generated by Django 3.1.7 on 2021-03-25 00:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_core', '0006_knowledge'),
    ]

    operations = [
        migrations.CreateModel(
            name='experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('compuny', models.CharField(max_length=100)),
                ('fromDate', models.CharField(max_length=50)),
                ('toDate', models.CharField(max_length=50)),
                ('desc', models.CharField(blank=True, max_length=500, null=True)),
                ('expFor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_core.profile')),
            ],
        ),
    ]
